apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-delivery
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/markffckyou12/cicd.git
    targetRevision: HEAD
    path: app-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
