# github-repo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-github
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: cicd-repo-manual
  url: https://github.com/markffckyou12/cicd.git
  username: markffckyou12
  password: Z2hwX2Nqb3duMHA2VWJpdkU3RExEZGRETEdT # <-- REPLACE with your actual Base64 PAT